-- Club Events Phase 0+1 — additive-only migration (CREATE TABLE IF NOT EXISTS style)
-- Matches backend/prisma/schema.prisma club_event_* models exactly.

CREATE TABLE IF NOT EXISTS `club_event_categories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name_ar` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kind` enum('competition','challenge','workshop','bootcamp','seminar','open_day','community','kids_activity','campaign') COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `show_in_app` tinyint(1) NOT NULL DEFAULT '1',
  `requires_approval` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_number` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `cover_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category_id` int NOT NULL,
  `kind` enum('competition','challenge','workshop','bootcamp','seminar','open_day','community','kids_activity','campaign') COLLATE utf8mb4_unicode_ci NOT NULL,
  `branch_id` int NOT NULL,
  `hall_id` int DEFAULT NULL,
  `venue_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_date` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_date` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_time` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `end_time` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_opens` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_closes` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_paused` tinyint(1) NOT NULL DEFAULT '0',
  `max_capacity` int NOT NULL DEFAULT '0',
  `waitlist_capacity` int NOT NULL DEFAULT '0',
  `visibility` enum('internal','members','public') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'members',
  `status` enum('draft','pending_approval','approved','rejected','published','ongoing','completed','closed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `is_free` tinyint(1) NOT NULL DEFAULT '0',
  `allow_guests` tinyint(1) NOT NULL DEFAULT '0',
  `requires_active_subscription` tinyint(1) NOT NULL DEFAULT '1',
  `min_age` int DEFAULT NULL,
  `max_age` int DEFAULT NULL,
  `requires_guardian_consent` tinyint(1) NOT NULL DEFAULT '0',
  `campaign_tag` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `show_in_app` tinyint(1) NOT NULL DEFAULT '0',
  `registrations_count` int NOT NULL DEFAULT '0',
  `attended_count` int NOT NULL DEFAULT '0',
  `closing_notes` text COLLATE utf8mb4_unicode_ci,
  `closed_by` int DEFAULT NULL,
  `closed_at` datetime(3) DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_at` datetime(3) DEFAULT NULL,
  `cancel_reason` text COLLATE utf8mb4_unicode_ci,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` int DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `club_events_event_number_key` (`event_number`),
  KEY `club_events_branch_id_idx` (`branch_id`),
  KEY `club_events_status_idx` (`status`),
  KEY `club_events_kind_idx` (`kind`),
  KEY `club_events_start_date_idx` (`start_date`),
  KEY `club_events_branch_id_status_is_deleted_idx` (`branch_id`,`status`,`is_deleted`),
  KEY `club_events_category_id_fkey` (`category_id`),
  CONSTRAINT `club_events_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `club_event_categories` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_id` int NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `session_date` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_time` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_time` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hall_id` int DEFAULT NULL,
  `trainer_id` int DEFAULT NULL,
  `max_capacity` int DEFAULT NULL,
  `order_index` int NOT NULL DEFAULT '0',
  `status` enum('scheduled','ongoing','completed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'scheduled',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `club_event_sessions_event_id_idx` (`event_id`),
  KEY `club_event_sessions_session_date_idx` (`session_date`),
  KEY `club_event_sessions_trainer_id_idx` (`trainer_id`),
  KEY `club_event_sessions_hall_id_session_date_idx` (`hall_id`,`session_date`),
  CONSTRAINT `club_event_sessions_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `club_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_ticket_tiers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_id` int NOT NULL,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `audience` enum('member','guest','lead') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `min_age` int DEFAULT NULL,
  `max_age` int DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `early_bird_price` decimal(10,2) DEFAULT NULL,
  `early_bird_until` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `capacity` int DEFAULT NULL,
  `sales_from` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sales_until` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `members_only` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `club_event_ticket_tiers_event_id_idx` (`event_id`),
  CONSTRAINT `club_event_ticket_tiers_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `club_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_registrations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `registration_number` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_id` int NOT NULL,
  `session_id` int DEFAULT NULL,
  `tier_id` int DEFAULT NULL,
  `registrant_type` enum('member','guest','lead') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'member',
  `member_id` int DEFAULT NULL,
  `guest_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guest_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guest_email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lead_source` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `converted_member_id` int DEFAULT NULL,
  `branch_id` int NOT NULL,
  `status` enum('pending_payment','confirmed','waitlisted','cancelled','refunded') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending_payment',
  `waitlist_position` int DEFAULT NULL,
  `hold_expires_at` datetime(3) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `discount_value` decimal(10,2) NOT NULL DEFAULT '0.00',
  `paid_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `checkin_code` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `participant_dob` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guardian_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guardian_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `guardian_relation` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consent_signed` tinyint(1) NOT NULL DEFAULT '0',
  `consent_file` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergency_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `channel` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `no_show` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `cancelled_at` datetime(3) DEFAULT NULL,
  `cancel_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` int DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `club_event_registrations_registration_number_key` (`registration_number`),
  UNIQUE KEY `club_event_registrations_checkin_code_key` (`checkin_code`),
  UNIQUE KEY `uq_event_member_session` (`event_id`,`member_id`,`session_id`),
  KEY `club_event_registrations_event_id_idx` (`event_id`),
  KEY `club_event_registrations_member_id_idx` (`member_id`),
  KEY `club_event_registrations_branch_id_idx` (`branch_id`),
  KEY `club_event_registrations_status_idx` (`status`),
  KEY `club_event_registrations_event_id_status_idx` (`event_id`,`status`),
  KEY `club_event_registrations_tier_id_fkey` (`tier_id`),
  CONSTRAINT `club_event_registrations_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `club_events` (`id`),
  CONSTRAINT `club_event_registrations_tier_id_fkey` FOREIGN KEY (`tier_id`) REFERENCES `club_event_ticket_tiers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payment_number` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `registration_id` int NOT NULL,
  `event_id` int NOT NULL,
  `branch_id` int NOT NULL,
  `type` enum('payment','refund') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'payment',
  `amount` decimal(10,2) NOT NULL,
  `payment_method` enum('cash','card','bank','online') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_date` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('pending','completed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'completed',
  `refund_of_id` int DEFAULT NULL,
  `idempotency_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_by` int DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `club_event_payments_payment_number_key` (`payment_number`),
  UNIQUE KEY `uq_payment_reg_idem` (`registration_id`,`idempotency_key`),
  KEY `club_event_payments_registration_id_idx` (`registration_id`),
  KEY `club_event_payments_event_id_idx` (`event_id`),
  KEY `club_event_payments_branch_id_payment_date_idx` (`branch_id`,`payment_date`),
  CONSTRAINT `club_event_payments_registration_id_fkey` FOREIGN KEY (`registration_id`) REFERENCES `club_event_registrations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_checkins` (
  `id` int NOT NULL AUTO_INCREMENT,
  `registration_id` int NOT NULL,
  `event_id` int NOT NULL,
  `session_id` int DEFAULT NULL,
  `method` enum('qr','member_code','manual') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'qr',
  `checked_in_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `checked_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_checkin_reg_session` (`registration_id`,`session_id`),
  KEY `club_event_checkins_event_id_idx` (`event_id`),
  KEY `club_event_checkins_session_id_idx` (`session_id`),
  CONSTRAINT `club_event_checkins_registration_id_fkey` FOREIGN KEY (`registration_id`) REFERENCES `club_event_registrations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `club_event_checkins_session_id_fkey` FOREIGN KEY (`session_id`) REFERENCES `club_event_sessions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_staff` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_id` int NOT NULL,
  `session_id` int DEFAULT NULL,
  `trainer_id` int DEFAULT NULL,
  `employee_id` int DEFAULT NULL,
  `external_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('lead_instructor','assistant','judge','coordinator','support') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'support',
  `notes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `club_event_staff_event_id_idx` (`event_id`),
  KEY `club_event_staff_trainer_id_idx` (`trainer_id`),
  KEY `club_event_staff_employee_id_idx` (`employee_id`),
  CONSTRAINT `club_event_staff_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `club_events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `club_event_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `refund_window_days` int NOT NULL DEFAULT '3',
  `waitlist_hold_hours` int NOT NULL DEFAULT '24',
  `approval_budget_threshold` decimal(10,2) DEFAULT NULL,
  `reminder_hours_before` int NOT NULL DEFAULT '24',
  `updated_by` int DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
