/** Generated from frontend locale files (nav.mos). */

export const MOS_LABELS_AR: Record<string, string> = {
  "instructorsRating": "تقييم المدربين",
  "benefitsReservations": "حجوزات المزايا",
  "appHomeScreenSections": "أقسام الشاشة الرئيسية للتطبيق",
  "requests": "الطلبات",
  "feedbacks": "آراء الأعضاء",
  "medicalMembershipsIncome": "دخل اشتراكات العيادة",
  "instructorsPayroll": "رواتب المدربين",
  "branchesVisits": "زيارات الفروع",
  "employeesRequests": "طلبات الموظفين",
  "classesScheduleImages": "صور جدول الكلاسات",
  "personalTraining": "التدريب الشخصي",
  "personalTrainingIncome": "دخل التدريب الشخصي",
  "trainersTimeTable": "جدول مواعيد المدربين",
  "reservation_types": "انواع الحجوزات",
  "fixedTrainerCommission": "العموله الثابته للمدرب",
  "membershipsIncomePerPackageType": "دخل الاشتراكات حسب نوع الباقة",
  "trainerMemberRetention": "تقرير احتفاظ المدرب للمشترك",
  "trainersReports": "تقارير المدربين",
  "multipleAttendancePerDay": "تكرار الحضور في اليوم",
  "profitSummary": "ملخص الأرباح",
  "consumedPTSessionsPerTrainer": "حصص التدريب الشخصي المستهلكة لكل مدرب",
  "consumedPTSessionsPerMembership": "حصص التدريب الشخصي المستهلكة لكل اشتراك",
  "trainerClosingRatioDetails": "تفاصيل نسبة إقناع المدرب",
  "trainerClosingRatio": "نسبة إقناع المدرب",
  "salesPersonClosingRatioDetails": "تفاصيل نسبة إغلاق المبيعات لكل موظف",
  "salesPersonClosingRatio": "نسبة إغلاق المبيعات لكل موظف",
  "instructorsClassesRates": "اسعار كلاسات المدربين",
  "employeeFinancial": "التقرير المالى للموظفين",
  "closingTransactions": "عمليات التقفيل",
  "membershipUpgrade": "ترقية الاشتراكات",
  "trainers": "المدربين الخاصين",
  "consumedPTSessions": "حصص التدريب الشخصي المستهلكة",
  "reminders": "التذكيرات",
  "freePrivateTraining": "التدريب الشخصى المجانى",
  "packageUtilizationPerSalesPersonal": "استخدام الباقات حسب موظف المبيعات",
  "maximumExpirationDate": "أقصى تاريخ انتهاء",
  "trainersAchievement": "إنجاز المدربين",
  "privateMemberships": "إشتراكات التدريب الشخصى",
  "membershipsDiscount": "خصومات الاشتراكات",
  "topActiveMembers": "الأعضاء الأكثر حضورًا",
  "notificationsTemplates": "الإشعارات",
  "packageCommission": "عمولة الباقات",
  "packagesCommissionsMonths": "عمولات مخصصه على العضويات",
  "tasks": "المهام",
  "staffPayroll": "دخول وخروج الموظفين",
  "membershipTransfer": "نقل الاشتراكات",
  "gymAttendanceCount": "عدد مرات حضور النادي",
  "benefitsConsumption": "استهلاك المزايا",
  "invitationCount": "الدعوات",
  "freeConsumedBenefits": "استهلاك المزايا المجانية",
  "salaries": "المرتبات",
  "employeesCommissions": "عمولات الموظفين",
  "workouts": "التدريبات",
  "blockedMembers": "الاعضاء المحظورين",
  "memberAttendance": "حضور الاعضاء",
  "memberReservationsOnClasses": "حجوزات الاعضاء للكلاسات",
  "membersAttendanceOnClasses": "حضور الاعضاء للكلاسات",
  "cancelledClasses": "الكلاسات الملغية",
  "classesbookingList": "قائمة حجوزات الكلاسات",
  "heldClasses": "عدد الكلاسات",
  "instructorDueAmount": "المبلغ المستحق لمدرب الكلاسات",
  "classesPerInstructorType": "الكلاسات لكل مدرب",
  "deletedReceipts": "الايصالات الملغية",
  "classes": "الكلاسات",
  "classesTypes": "اسماء الكلاسات",
  "otherEntitiesBookings": "حجوزات جهات أخرى",
  "about": "من نحن",
  "absentMembers": "الأعضاء الغائبون",
  "accounts": "الحسابات",
  "accountsManagement": "إدارة الحسابات",
  "admin": "التحكم",
  "advances": "السلف",
  "announcements": "الإعلانات",
  "approveDecline": "الموافقة أو الرفض",
  "benefits": "المزايا",
  "birthdays": "أعياد الميلاد",
  "bonus": "علاوات الموظفين",
  "cafeteria": "الكافيتيريا",
  "call_feedbacks": "نتائج المكالمات",
  "callFeedbacks": "نتائج المكالمات",
  "callFeedbackDetails": "تفاصيل نتائج المكالمات",
  "calls": "المكالمات",
  "customerMessaging": "مراسلة العملاء",
  "callsSummary": "ملخص المكالمات",
  "class_cancellation_reasons": "أسباب إلغاء الكلاس",
  "class_rooms": "غرف الكلاسات",
  "classesSched": "جدول الكلاسات",
  "classes_types": "أنواع الحصص",
  "className": "اسم الكلاس",
  "class_services": "خدمات الحصص",
  "serviceName": "اسم الخدمة",
  "price": "السعر",
  "status": "الحالة",
  "active": "نشط",
  "inactive": "غير نشط",
  "classes_genres": "انواع الكلاس",
  "classes_programs": "برامج الكلاس",
  "commission": "العمولات",
  "complaintsAndSuggestions": "الشكاوى والاقتراحات",
  "complaintDetails": "تفاصيل الشكوى",
  "dashboard": "لوحة المعلومات",
  "myDashboard": "لوحتي",
  "dataList": "قوائم البيانات",
  "daybydayprofit": "الأرباح يومًا بيوم",
  "debts": "الديون",
  "deductions": "الخصومات",
  "events": "الأحداث",
  "expenses": "المصروفات",
  "expenses_types": "انواع المصروفات",
  "extra": "المزيد",
  "freeBenefits": "المزايا المجانية",
  "gymImages": "صور التطبيق",
  "gymRules": "الشروط والأحكام",
  "gymSettings": "الإعدادات",
  "gym_sections": "القطاعات",
  "instructorData": "بيانات المدرب",
  "instructors": "المدربين",
  "interest_percentages": "نسب الإهتمام",
  "invitations": "الدعوات",
  "job_titles": "المسميات الوظيفية",
  "locations_inside_gym": "الاماكن",
  "logs": "السجلات",
  "lostItems": "العناصر المفقودة",
  "lost_category": "تصنيف المفقود",
  "machineMaintenance": "صيانة الأجهزة",
  "machine_models": "نوع الجهاز",
  "machines": "الاجهزة",
  "management": "إدارة الحصص",
  "additionalManagement": "إضافي",
  "nutritionManagement": "إدارة التغذية",
  "nutritionServiceTypes": "أنواع خدمات التغذية",
  "nutritionSchedulingBookings": "جدولة وحجوزات التغذية",
  "spaManagement": "إدارة السبا",
  "spaServiceTypes": "أنواع خدمات السبا",
  "spaSchedulingBookings": "جدولة وحجوزات السبا",
  "personalTrainingManagement": "إدارة التدريب الشخصي",
  "personalTrainingServiceTypes": "أنواع خدمات التدريب الشخصي",
  "personalTrainingSchedulingBookings": "جدولة وحجوزات التدريب الشخصي",
  "monthlySchedules": "الجداول الشهرية",
  "bookings": "الحجوزات",
  "bookingSystemBoard": "لوحة نظام الحجز",
  "appointmentManagement": "إدارة المواعيد",
  "availableAppointments": "المواعيد المتاحة",
  "appManagement": "إدارة التطبيق",
  "aboutApp": "عن التطبيق",
  "memAtten": "حضور الأعضاء",
  "memberEntry": "دخول الأعضاء",
  "memberNotifications": "إشعارات الأعضاء",
  "member_level": "مستوى العضو",
  "members": "الأعضاء",
  "membershipManagement": "إدارة العضوية",
  "subscriptionTypes": "أنواع الاشتراكات",
  "reception": "الاستقبال",
  "membersData": "بيانات الأعضاء",
  "membership_cancellation_reasons": "أسباب إلغاء العضوية",
  "memberships": "الاشتراكات",
  "membershipsLog": "سجل الإشتراكات",
  "nationalities": "الجنسيات",
  "regions": "المناطق",
  "newRenewedmemberships": "الاشتراكات الجديدة والمجددة",
  "news": "الأخبار",
  "notActiveMembers": "الأعضاء غير النشطين",
  "notRenewedmemberships": "الاشتراكات غير المجددة",
  "offers": "العروض",
  "dailySchedule": "جدول يومى",
  "membersApp": "تطبيق الاعضاء",
  "onePassService": "الخدمات الواحدة",
  "otherRevenue": "الإيرادات الإخرى",
  "overAttendance": "تجاوز حد الحضور",
  "owners": "الملاك",
  "package_type": "نوع العضوية",
  "packages": "العضويات",
  "packagesUtil": "استخدام الباقات",
  "percentages": "النسب المئوية",
  "salesPercentages": "النسبه المئوية لموظفى المبيعات",
  "coachPercentages": "النسب المئوية للمدربين ",
  "permissions": "الصلاحيات",
  "potMembers": "الأعضاء المحتملين",
  "profit": "الأرباح",
  "membershipsIncome": "دخل اشتراكات النادي",
  "privateMembershipsIncome": "دخل الاشتراكات الخاصه",
  "ranges": "الأمتدادات",
  "salesRanges": "الأمتدادات لموظفى المبيعات",
  "coachRanges": "الأمتدادات للمدربين",
  "receipts": "الإيصالات",
  "reports": "التقارير",
  "requiredFields": "حقول الصفحة",
  "requiredFieldsMemberProfile": "ملف العضو الشخصي",
  "requiredFieldsPossibleMembers": "الأعضاء المحتملين",
  "roles": "الأدوار",
  "salesCommission": "عمولة موظفي المبيعات",
  "sessionTypes": "نوع الحصص",
  "sessions": "الخدمات الواحدة",
  "shifts": "اوقات الموظفين",
  "sources_of_knowledge": "مصادر المعرفة",
  "staff": "الموظفين",
  "staffAtt": "حضور الموظفين",
  "staffAttendance": "حضور الموظفين",
  "staffData": "بيانات الموظفين",
  "employeeSettings": "إعدادات الموظفين",
  "settingsManagement": "الإعدادات",
  "employeeNationalities": "الجنسيات",
  "employeeReligions": "الديانات",
  "employeeSocialStatuses": "الحالات الاجتماعية",
  "userManagement": "إدارة المستخدمين",
  "companyData": "بيانات الشركة",
  "employeeBranches": "الفروع",
  "employeeJobTitles": "المسميات الوظيفية",
  "gymPolicies": "سياسات النادي",
  "salesStaffSettings": "موظفو المبيعات",
  "customerSourcesSettings": "مصادر المعرفة",
  "employeeAudit": "سجل التدقيق",
  "staffHolidays": "اجازات الموظفين",
  "targets": "الأهداف",
  "salesTargets": "الاهداف لموظفى المبيعات",
  "coachTargets": "الاهداف للمدربين",
  "trainerCommission": "عمولة المدربين",
  "transformationImages": "صور التحولات",
  "users": "المستخدمون",
  "visa_types": "انواع المصاريف",
  "exercises": "التمارين",
  "faqs": "الأسئلة الشائعة",
  "member_goals": "اهادف العضو",
  "salesSchedule": "جدول موظفى المبيعات",
  "suit_size": "حجم البدلة",
  "trainerSchedule": "جدول المدربين",
  "TRAINERS_SCHEDULE": "جدول المدربين",
  "doctorsSchedule": "جدول الأطباء",
  "DOCTORS_SCHEDULE": "جدول الأطباء",
  "inbodyMeasurements": "قياسات InBody",
  "workout_types": "انواع التدريب",
  "maintenance_types": "انواع الصيانة",
  "expensesTypes": "أنواع المصروفات",
  "schedulingEngine": "الجدولة والحجوزات",
  "bookingsEngine": "الحجوزات",
  "serviceSettingsNav": "إعدادات الخدمات",
  "inbodyRecordsNav": "سجلات الإنبودي",
  "schedDashboard": "لوحة التحكم",
  "schedClasses": "الحصص",
  "schedZumba": "زومبا",
  "schedSpa": "سبا",
  "schedInbody": "إنبودي",
  "schedAdditional": "خدمات إضافية",
  "bookClasses": "الحصص",
  "bookZumba": "زومبا",
  "bookSpa": "سبا",
  "bookInbody": "إنبودي",
  "bookAdditional": "خدمات إضافية",
  "schedHub": "الكلاسات",
  "classSchedulingBookings": "جدولة وحجوزات الحصص",
  "classSchedulingHome": "لوحة نظام الحجز",
  "classMonthlySchedules": "الجداول الشهرية",
  "classScheduleSlots": "إدارة المواعيد",
  "classAdditionalServices": "الخدمات الإضافية",
  "classScheduleBookings": "حجوزات الكلاسات",
  "classAvailableSlots": "المواعيد المتاحة"
};

export const MOS_LABELS_EN: Record<string, string> = {
  "instructorsRating": "Instructors Rating",
  "benefitsReservations": "Benefits Reservations",
  "appHomeScreenSections": "App Home Screen Sections",
  "feedbacks": "Member Feedback",
  "requests": "Requests",
  "medicalMembershipsIncome": "Medical Memberships Income",
  "instructorsPayroll": "Instructors Payroll",
  "branchesVisits": "Branches Visits",
  "employeesRequests": "Employees Requests",
  "classesScheduleImages": "Classes Schedule Images",
  "trainersTimeTable": "Trainers Time Table",
  "reservation_types": "Reservation Types",
  "fixedTrainerCommission": "Fixed Trainer Commission",
  "membershipsIncomePerPackageType": "Memberships Income Per Package Type",
  "trainerMemberRetention": "Trainer Member Retention",
  "trainersReports": "Trainers Reports",
  "multipleAttendancePerDay": "Multiple Attendance Per Day",
  "profitSummary": "Profit Summary",
  "consumedPTSessionsPerTrainer": "Consumed PT Sessions Per Trainer",
  "consumedPTSessionsPerMembership": "Consumed PT Sessions Per Membership",
  "trainerClosingRatioDetails": "Trainer Closing Ratio Details",
  "trainerClosingRatio": "Trainer Closing Ratio",
  "salesPersonClosingRatioDetails": "Sales Person Closing Ratio Details",
  "salesPersonClosingRatio": "Sales Person Closing Ratio",
  "instructorsClassesRates": "Instructors Classes Rates",
  "employeeFinancial": "Employee Financial",
  "closingTransactions": "Closing Transactions",
  "membershipUpgrade": "Membership Upgrade",
  "trainers": "Trainers",
  "consumedPTSessions": "Consumed PT Sessions",
  "reminders": "Reminders",
  "freePrivateTraining": "Orientation PT Sessions",
  "packageUtilizationPerSalesPersonal": "Package Utilization Per Sales Personal",
  "maximumExpirationDate": "Maximum Expiration Date",
  "trainersAchievement": "Trainers Achievement",
  "personalTraining": "Personal Training",
  "membershipsDiscount": "Memberships Discount",
  "topActiveMembers": "Top Active Members",
  "notificationsTemplates": "Notifications Templates",
  "packageCommission": "Package Commission",
  "packagesCommissionsMonths": "Custom Packages Commissions",
  "tasks": "Tasks",
  "staffPayroll": "Staff In - Out",
  "membershipTransfer": "Membership Transfer",
  "gymAttendanceCount": "Gym Attendance Count",
  "benefitsConsumption": "Benefits Consumption",
  "invitationCount": "Invitations",
  "freeConsumedBenefits": "Free Consumed Benefits",
  "salaries": "Salaries",
  "employeesCommissions": "Employees Commissions",
  "blockedMembers": "Blocked Members",
  "memberAttendance": "Member Attendance",
  "memberReservationsOnClasses": "Member Reservations",
  "membersAttendanceOnClasses": "Attendance On Classes",
  "cancelledClasses": "Cancelled Classes",
  "classesbookingList": "Classes Booking List",
  "deletedReceipts": "Deleted Receipts",
  "classesPerInstructorType": "Classes Per Instructor/Type",
  "classes": "Classes",
  "heldClasses": "Held Classes",
  "instructorDueAmount": "Instructor Due Amount",
  "classesTypes": "Classes Names",
  "otherEntitiesBookings": "Other entities bookings",
  "workouts": "Workouts",
  "faqs": "FAQs",
  "exercises": "Exercises",
  "member_goals": "Member Goals",
  "suit_size": "Suit Size",
  "workout_types": "Workout Types",
  "maintenance_types": "Maintenance Types",
  "salesSchedule": "Sales Schedule",
  "trainerSchedule": "Trainer Schedule",
  "TRAINERS_SCHEDULE": "Trainer Schedule",
  "doctorsSchedule": "Doctors Schedule",
  "DOCTORS_SCHEDULE": "Doctors Schedule",
  "inbodyMeasurements": "InBody Measurements",
  "absentMembers": "Absent Members",
  "logs": "Logs",
  "machineMaintenance": "Machine Maintenance",
  "complaintDetails": "Complaint Details",
  "machines": "Machines",
  "lostItems": "Lost Items",
  "machine_models": "Machine Models",
  "lost_category": "Lost Category",
  "gymSettings": "Settings",
  "locations_inside_gym": "Locations",
  "complaintsAndSuggestions": "Complaints & Suggestions",
  "requiredFields": "Page Fields",
  "requiredFieldsMemberProfile": "Member Profile",
  "requiredFieldsPossibleMembers": "Possible Members",
  "approveDecline": "Approve / Decline",
  "memberNotifications": "Member Notifications",
  "dataList": "Data List",
  "classes_types": "Class Types",
  "className": "Class Name",
  "class_services": "Class Services",
  "serviceName": "Service Name",
  "price": "Price",
  "status": "Status",
  "active": "Active",
  "inactive": "Inactive",
  "classes_genres": "Classes Genres",
  "classes_programs": "Classes Programs",
  "gym_sections": "Sections",
  "sources_of_knowledge": "Sources of Knowledge",
  "owners": "Owners",
  "nationalities": "Nationalities",
  "regions": "Regions",
  "visa_types": "Visa Types",
  "job_titles": "Job Titles",
  "call_feedbacks": "Call Feedbacks",
  "class_rooms": "Class Rooms",
  "class_cancellation_reasons": "Class Cancellation Reasons",
  "membership_cancellation_reasons": "Membership Cancellation Reasons",
  "interest_percentages": "Interest Percentages",
  "transformationImages": "Transformation Images",
  "news": "News",
  "events": "Events",
  "offers": "Offers",
  "dailySchedule": "Daily Schedule",
  "freeBenefits": "Free Benefits",
  "gymImages": "App Images",
  "receipts": "Receipts",
  "benefits": "Benefits",
  "membersApp": "Members App",
  "expenses_types": "Expenses Types",
  "package_type": "Package Type",
  "member_level": "Member Level",
  "gymRules": "Terms and Conditions",
  "sessionTypes": "Session Types",
  "commission": "Commission",
  "ranges": "Ranges",
  "salesRanges": "Sales Ranges",
  "coachRanges": "Coach Ranges",
  "percentages": "Percentages",
  "salesPercentages": "Sales Percentages",
  "coachPercentages": "Coach Percentages",
  "targets": "Targets",
  "salesTargets": "Sales Targets",
  "coachTargets": "Coach Targets",
  "announcements": "Announcements",
  "accounts": "Accounts",
  "accountsManagement": "Accounts Management",
  "otherRevenue": "Other Revenue",
  "expenses": "Expenses",
  "deductions": "Deductions",
  "advances": "Advances",
  "bonus": "Bonus",
  "dashboard": "Dashboard",
  "myDashboard": "My dashboard",
  "members": "Members",
  "membershipManagement": "Membership Management",
  "subscriptionTypes": "Subscription Types",
  "reception": "Reception",
  "membersData": "Members Data",
  "sessions": "Sessions",
  "onePassService": "One Pass Service",
  "extra": "Extra",
  "management": "Class Management",
  "additionalManagement": "Additional",
  "nutritionManagement": "Nutrition Management",
  "nutritionServiceTypes": "Nutrition Service Types",
  "nutritionSchedulingBookings": "Nutrition Scheduling & Bookings",
  "spaManagement": "SPA Management",
  "spaServiceTypes": "SPA Service Types",
  "spaSchedulingBookings": "SPA Scheduling & Bookings",
  "personalTrainingManagement": "Personal Training Management",
  "personalTrainingServiceTypes": "Personal Training Service Types",
  "personalTrainingSchedulingBookings": "Personal Training Scheduling & Bookings",
  "monthlySchedules": "Monthly Schedules",
  "bookings": "Bookings",
  "bookingSystemBoard": "Booking System Board",
  "appointmentManagement": "Appointment Management",
  "availableAppointments": "Available Appointments",
  "appManagement": "App Management",
  "aboutApp": "About the App",
  "reports": "Reports",
  "memberships": "Memberships",
  "notRenewedmemberships": "Not Renewed Memberships",
  "newRenewedmemberships": "New/Renew Memberships",
  "membershipsLog": "Memberships Log",
  "memAtten": "Member Attendance",
  "memberEntry": "Member Entry",
  "admin": "Administration",
  "about": "About",
  "profit": "Profit",
  "membershipsIncome": "Gym Memberships Income",
  "personalTrainingIncome": "Personal Training Income",
  "packagesUtil": "Packages Utilization",
  "daybydayprofit": "Day By Day Profit",
  "birthdays": "Birthdays",
  "callsSummary": "Calls Summary",
  "notActiveMembers": "Not Active Members",
  "overAttendance": "Over Attendance",
  "debts": "Debts",
  "salesCommission": "Sales Commission",
  "trainerCommission": "Trainer Commission",
  "cafeteria": "Cafeteria",
  "calls": "Calls",
  "customerMessaging": "Customer Messaging",
  "invitations": "Invitations",
  "classesSched": "Classes Schedule",
  "potMembers": "Potential Members",
  "permissions": "Permissions",
  "roles": "Roles",
  "users": "Users",
  "staff": "Staff",
  "staffData": "Staff Data",
  "employeeSettings": "Staff Settings",
  "settingsManagement": "Settings",
  "employeeNationalities": "Nationalities",
  "employeeReligions": "Religions",
  "employeeSocialStatuses": "Marital Statuses",
  "userManagement": "User Management",
  "companyData": "Company Data",
  "employeeBranches": "Branches",
  "employeeJobTitles": "Job Titles",
  "gymPolicies": "Gym Policies",
  "salesStaffSettings": "Sales Staff",
  "customerSourcesSettings": "Knowledge Sources",
  "employeeAudit": "Audit Log",
  "instructorData": "Instructor Data",
  "staffAtt": "Staff Attendance",
  "staffHolidays": "Staff Holidays",
  "shifts": "Shifts",
  "instructors": "Instructors",
  "staffAttendance": "Staff Attendance",
  "packages": "Packages",
  "privateMemberships": "Personal Training Memberships",
  "callFeedbacks": "Call Feedbacks",
  "callFeedbackDetails": "Call Feedback Details",
  "privateMembershipsIncome": "Personal Training Income",
  "expensesTypes": "Expense Types",
  "schedulingEngine": "Scheduling & Bookings",
  "bookingsEngine": "Bookings",
  "serviceSettingsNav": "Service Settings",
  "inbodyRecordsNav": "InBody Records",
  "schedDashboard": "Dashboard",
  "schedClasses": "Classes",
  "schedZumba": "Zumba",
  "schedSpa": "SPA",
  "schedInbody": "InBody",
  "schedAdditional": "Additional Services",
  "bookClasses": "Classes",
  "bookZumba": "Zumba",
  "bookSpa": "SPA",
  "bookInbody": "InBody",
  "bookAdditional": "Additional Services",
  "schedHub": "Classes",
  "classSchedulingBookings": "Class Scheduling & Bookings",
  "classSchedulingHome": "Booking System Dashboard",
  "classMonthlySchedules": "Monthly Schedules",
  "classScheduleSlots": "Schedule Slots",
  "classAdditionalServices": "Additional Services",
  "classScheduleBookings": "Class Bookings",
  "classAvailableSlots": "Available Slots"
};
