export interface MosEntityConfig {
  key: string;
  model: string;
  defaultWhere?: Record<string, unknown>;
  /** Values forced only on create when list filtering is broader than one discriminator. */
  createData?: Record<string, unknown>;
  searchFields: string[];
  requiredOnCreate: string[];
  writable: string[];
  dateField?: string;
  orderBy?: Record<string, 'asc' | 'desc'>;
}

const BASE_WRITABLE = [
  'branchId',
  'notes',
  'status',
];

export const MOS_ENTITIES: Record<string, MosEntityConfig> = {
  leads: {
    key: 'leads',
    model: 'club_leads',
    searchFields: ['name', 'phone', 'email'],
    requiredOnCreate: ['name'],
    writable: ['name', 'phone', 'email', 'gender', 'sourceId', 'branchId', 'status', 'notes', 'followUpAt', 'assignedTo'],
    orderBy: { id: 'desc' },
  },
  calls: {
    key: 'calls',
    model: 'club_calls',
    searchFields: ['member_name', 'phone', 'subject', 'staff_name'],
    requiredOnCreate: ['callDate'],
    writable: ['memberId', 'memberName', 'phone', 'callDate', 'callTime', 'subject', 'notes', 'outcome', 'staffName', 'branchId'],
    orderBy: { call_date: 'desc' },
  },
  invitations: {
    key: 'invitations',
    model: 'club_invitations',
    searchFields: ['invitee_name', 'invitee_phone', 'invited_by_name'],
    requiredOnCreate: ['inviteeName'],
    writable: ['inviteeName', 'inviteePhone', 'inviteeGender', 'invitedById', 'invitedByName', 'visitDate', 'status', 'branchId', 'notes'],
    orderBy: { id: 'desc' },
  },
  complaints: {
    key: 'complaints',
    model: 'club_tickets',
    defaultWhere: { ticket_type: { in: ['complaint', 'feedback'] } },
    createData: { ticket_type: 'complaint' },
    searchFields: ['member_name', 'subject', 'staff_name'],
    requiredOnCreate: ['subject'],
    writable: ['memberId', 'memberName', 'subject', 'body', 'status', 'priority', 'branchId', 'staffName'],
    orderBy: { id: 'desc' },
  },
  requests: {
    key: 'requests',
    model: 'club_tickets',
    defaultWhere: { ticket_type: 'request' },
    searchFields: ['member_name', 'subject'],
    requiredOnCreate: ['subject'],
    writable: ['memberId', 'memberName', 'subject', 'body', 'status', 'priority', 'branchId', 'staffName'],
    orderBy: { id: 'desc' },
  },
  feedbacks: {
    key: 'feedbacks',
    model: 'club_tickets',
    defaultWhere: { ticket_type: 'feedback' },
    searchFields: ['member_name', 'subject'],
    requiredOnCreate: ['subject'],
    writable: ['memberId', 'memberName', 'subject', 'body', 'status', 'priority', 'branchId', 'staffName'],
    orderBy: { id: 'desc' },
  },
  'free-benefits': {
    key: 'free-benefits',
    model: 'club_free_benefits',
    searchFields: ['member_name', 'benefit_name'],
    requiredOnCreate: ['benefitName', 'benefitDate'],
    writable: ['memberId', 'memberName', 'benefitName', 'benefitDate', 'quantity', 'branchId', 'notes'],
    orderBy: { benefit_date: 'desc' },
  },
  'approve-decline': {
    key: 'approve-decline',
    model: 'club_approval_items',
    searchFields: ['title', 'requested_by', 'entity_type'],
    requiredOnCreate: ['title'],
    writable: ['entityType', 'entityId', 'title', 'description', 'status', 'requestedBy', 'reviewedBy', 'reviewedAt', 'branchId', 'metadata'],
    orderBy: { id: 'desc' },
  },
  'machine-maintenance': {
    key: 'machine-maintenance',
    model: 'club_machine_maintenance',
    searchFields: ['machine_name', 'maintenance_type', 'notes'],
    requiredOnCreate: ['maintenanceDate'],
    writable: ['machineId', 'machineName', 'maintenanceDate', 'maintenanceType', 'cost', 'notes', 'branchId', 'status'],
    orderBy: { maintenance_date: 'desc' },
  },
  workouts: {
    key: 'workouts',
    model: 'club_workouts',
    searchFields: ['title', 'member_name', 'trainer_name'],
    requiredOnCreate: ['title'],
    writable: ['title', 'workoutType', 'trainerName', 'memberId', 'memberName', 'workoutDate', 'notes', 'branchId'],
    orderBy: { id: 'desc' },
  },
  reminders: {
    key: 'reminders',
    model: 'club_reminders',
    searchFields: ['member_name', 'title'],
    requiredOnCreate: ['title', 'reminderDate'],
    writable: ['memberId', 'memberName', 'title', 'reminderDate', 'reminderTime', 'channel', 'status', 'notes', 'branchId'],
    orderBy: { reminder_date: 'desc' },
  },
  'branch-visit': {
    key: 'branch-visit',
    model: 'club_branch_visits',
    searchFields: ['member_name', 'notes'],
    requiredOnCreate: ['visitDate'],
    writable: ['memberId', 'memberName', 'branchId', 'visitDate', 'visitTime', 'notes'],
    orderBy: { visit_date: 'desc' },
  },
  sessions: {
    key: 'sessions',
    model: 'club_one_pass_sessions',
    searchFields: ['member_name', 'service_name'],
    requiredOnCreate: ['sessionDate'],
    writable: ['memberId', 'memberName', 'sessionDate', 'serviceName', 'amount', 'branchId', 'status', 'notes'],
    orderBy: { session_date: 'desc' },
  },
  'class-rooms': {
    key: 'class-rooms',
    model: 'club_class_rooms',
    searchFields: ['name', 'code'],
    requiredOnCreate: ['name'],
    writable: ['name', 'code', 'capacity', 'branchId', 'isActive'],
    orderBy: { name: 'asc' },
  },
  machines: {
    key: 'machines',
    model: 'club_machines',
    searchFields: ['name', 'serial_number', 'model_name'],
    requiredOnCreate: ['name'],
    writable: ['name', 'serialNumber', 'modelName', 'branchId', 'status'],
    orderBy: { name: 'asc' },
  },
  shifts: {
    key: 'shifts',
    model: 'club_shifts',
    searchFields: ['name'],
    requiredOnCreate: ['name', 'startTime', 'endTime'],
    writable: ['name', 'startTime', 'endTime', 'branchId', 'isActive'],
    orderBy: { name: 'asc' },
  },
  'employees-requests': {
    key: 'employees-requests',
    model: 'club_employee_requests',
    searchFields: ['employee_name', 'subject', 'request_type'],
    requiredOnCreate: ['employeeName', 'requestType', 'subject'],
    writable: ['employeeId', 'employeeName', 'requestType', 'subject', 'body', 'status', 'branchId'],
    orderBy: { id: 'desc' },
  },
  'closing-transactions': {
    key: 'closing-transactions',
    model: 'club_closing_transactions',
    searchFields: ['closed_by', 'notes'],
    requiredOnCreate: ['closingDate', 'totalCash', 'totalCard'],
    writable: ['closingDate', 'branchId', 'totalCash', 'totalCard', 'totalOther', 'notes', 'closedBy'],
    orderBy: { closing_date: 'desc' },
  },
  'other-revenue': {
    key: 'other-revenue',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'other_revenue' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  expenses: {
    key: 'expenses',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'expense' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    dateField: 'entry_date',
    orderBy: { entry_date: 'desc' },
  },
  deductions: {
    key: 'deductions',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'deduction' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  advances: {
    key: 'advances',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'advance' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  bonus: {
    key: 'bonus',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'bonus' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  salaries: {
    key: 'salaries',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'salary' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  'employees-commissions': {
    key: 'employees-commissions',
    model: 'club_financial_entries',
    defaultWhere: { entry_type: 'employee_commission' },
    searchFields: ['title', 'employee_name'],
    requiredOnCreate: ['title', 'amount', 'entryDate'],
    writable: ['title', 'amount', 'entryDate', 'employeeId', 'employeeName', 'branchId', 'paymentMethod', 'notes', 'status'],
    orderBy: { entry_date: 'desc' },
  },
  announcements: {
    key: 'announcements',
    model: 'club_content_items',
    defaultWhere: { content_type: 'announcement' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'imageUrl', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  offers: {
    key: 'offers',
    model: 'club_content_items',
    defaultWhere: { content_type: 'offer' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'imageUrl', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  faqs: {
    key: 'faqs',
    model: 'club_content_items',
    defaultWhere: { content_type: 'faq' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  exercises: {
    key: 'exercises',
    model: 'club_content_items',
    defaultWhere: { content_type: 'exercise' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'imageUrl', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  'gym-rules': {
    key: 'gym-rules',
    model: 'club_content_items',
    defaultWhere: {
      content_type: 'gym_rule',
      NOT: [
        { title: { contains: 'خصوص' } },
        { title: { contains: 'privacy' } },
      ],
    },
    createData: { content_type: 'gym_rule' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  'about-app': {
    key: 'about-app',
    model: 'club_content_items',
    defaultWhere: {
      content_type: 'app_home_section',
      metadata: { path: '$.documentType', equals: 'about_app' },
    },
    createData: {
      content_type: 'app_home_section',
      metadata: { documentType: 'about_app' },
    },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'imageUrl', 'sortOrder', 'isActive', 'branchId'],
    orderBy: { sort_order: 'asc' },
  },
  'gym-images': {
    key: 'gym-images',
    model: 'club_content_items',
    defaultWhere: { content_type: 'gym_image' },
    searchFields: ['title'],
    requiredOnCreate: ['title'],
    writable: ['title', 'imageUrl', 'sortOrder', 'isActive', 'branchId'],
    orderBy: { sort_order: 'asc' },
  },
  'classes-schedule-images': {
    key: 'classes-schedule-images',
    model: 'club_content_items',
    defaultWhere: { content_type: 'schedule_image' },
    searchFields: ['title'],
    requiredOnCreate: ['title'],
    writable: ['title', 'imageUrl', 'sortOrder', 'isActive', 'branchId'],
    orderBy: { sort_order: 'asc' },
  },
  'trans-images': {
    key: 'trans-images',
    model: 'club_content_items',
    defaultWhere: { content_type: 'transformation_image' },
    searchFields: ['title'],
    requiredOnCreate: ['title'],
    writable: ['title', 'imageUrl', 'sortOrder', 'isActive', 'branchId'],
    orderBy: { sort_order: 'asc' },
  },
  'app-home-sections': {
    key: 'app-home-sections',
    model: 'club_content_items',
    defaultWhere: { content_type: 'app_home_section' },
    searchFields: ['title'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'imageUrl', 'sortOrder', 'isActive', 'branchId', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  'member-notifications': {
    key: 'member-notifications',
    model: 'club_content_items',
    defaultWhere: { content_type: 'notification_template' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'isActive', 'branchId', 'metadata'],
    orderBy: { id: 'desc' },
  },
  'possible-members-fields': {
    key: 'possible-members-fields',
    model: 'club_content_items',
    defaultWhere: { content_type: 'possible_member_field' },
    searchFields: ['title'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'sortOrder', 'isActive', 'metadata'],
    orderBy: { sort_order: 'asc' },
  },
  'notifications-templates': {
    key: 'notifications-templates',
    model: 'club_content_items',
    defaultWhere: { content_type: 'notification_template' },
    searchFields: ['title', 'body'],
    requiredOnCreate: ['title'],
    writable: ['title', 'body', 'isActive', 'branchId', 'metadata'],
    orderBy: { id: 'desc' },
  },
  'sales-ranges': {
    key: 'sales-ranges',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'sales_range' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'sales-percentages': {
    key: 'sales-percentages',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'sales_percentage' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'sales-targets': {
    key: 'sales-targets',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'sales_target' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'coach-ranges': {
    key: 'coach-ranges',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'trainer_range' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'coach-percentages': {
    key: 'coach-percentages',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'trainer_percentage' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'coach-targets': {
    key: 'coach-targets',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'trainer_target' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'instructors-classes-prices': {
    key: 'instructors-classes-prices',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'instructor_class_rate' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
  'packages-commissions': {
    key: 'packages-commissions',
    model: 'club_commission_rules',
    defaultWhere: { kind: 'package_commission' },
    searchFields: ['name'],
    requiredOnCreate: ['name', 'config'],
    writable: ['name', 'config', 'branchId', 'isActive'],
    orderBy: { id: 'desc' },
  },
};

/** Path slug → entity registry key */
export const MOS_PATH_ENTITY: Record<string, string> = {
  'potential-members': 'leads',
  calls: 'calls',
  invitations: 'invitations',
  complaints: 'complaints',
  requests: 'requests',
  feedbacks: 'feedbacks',
  'free-benefits': 'free-benefits',
  'approve-decline': 'approve-decline',
  'machine-maintenance': 'machine-maintenance',
  workouts: 'workouts',
  reminders: 'reminders',
  'branch-visit': 'branch-visit',
  sessions: 'sessions',
  'class-rooms': 'class-rooms',
  shifts: 'shifts',
  'employees-requests': 'employees-requests',
  'management/machines': 'machines',
  'management/closing-Transactions': 'closing-transactions',
  'management/announcements': 'announcements',
  'management/faqs': 'faqs',
  'management/exercises': 'exercises',
  'management/gym-rules': 'gym-rules',
  about: 'about-app',
  'administration/gym-images': 'gym-images',
  'administration/classes-schedule-images': 'classes-schedule-images',
  'administration/trans-images': 'trans-images',
  'management/appHomeScreenSections': 'app-home-sections',
  'management/member-notifications': 'member-notifications',
  'management/possible-members-fields': 'possible-members-fields',
  'management/notifications-Templates': 'notifications-templates',
  'management/salesRanges': 'sales-ranges',
  'management/salesPercentages': 'sales-percentages',
  'management/salesTargets': 'sales-targets',
  'management/coachRanges': 'coach-ranges',
  'management/coachPercentages': 'coach-percentages',
  'management/coachTargets': 'coach-targets',
  'management/instructors-Classes-Prices': 'instructors-classes-prices',
  'management/packages-commissions': 'packages-commissions',
  'accounts/other-revenue': 'other-revenue',
  'accounts/expenses': 'expenses',
  'accounts/deductions': 'deductions',
  'accounts/advances': 'advances',
  'accounts/bonus': 'bonus',
  'accounts/salaries': 'salaries',
  'accounts/employeesCommissions': 'employees-commissions',
};

export const MOS_LOOKUP_PATHS: Record<string, string> = {
  'management/class-genres': 'class_genre',
  'management/class-programs': 'class_program',
  'management/classes-types': 'class_type',
  'management/gym-sections': 'gym_section',
  'management/expenses-types': 'expense_type',
  'management/owners': 'owner',
  'management/nationalities': 'nationality',
  'management/regions': 'region',
  'management/visa-types': 'visa_type',
  'management/job-titles': 'job_title',
  'management/call-feedbacks': 'call_feedback',
  'management/class-cancellation-reasons': 'class_cancel_reason',
  'management/membership-cancellation-reasons': 'membership_cancel_reason',
  'management/interest-percentages': 'interest_percentage',
  'management/gym-locations': 'gym_location',
  'management/lost-category': 'lost_category',
  'management/machine-models': 'machine_model',
  'management/package-type': 'package_type',
  'management/member-level': 'member_level',
  'management/suit-size': 'suit_size',
  'management/member-goals': 'member_goal',
  'management/session-types': 'session_type',
  'management/workout-types': 'workout_type',
  'management/maintenance-types': 'maintenance_type',
  'management/reservation-types': 'reservation_type',
};

export function entityKeyFromPath(mosPath: string): string | null {
  const normalized = mosPath.replace(/^\/mos\/?/, '').replace(/\/$/, '');
  return MOS_PATH_ENTITY[normalized] ?? null;
}

export function lookupCategoryFromPath(mosPath: string): string | null {
  const normalized = mosPath.replace(/^\/mos\/?/, '').replace(/\/$/, '');
  return MOS_LOOKUP_PATHS[normalized] ?? null;
}

export function listEntityKeys(): string[] {
  return Object.keys(MOS_ENTITIES);
}

// Ensure BASE_WRITABLE is referenced (shared field hints for frontend)
export const MOS_COMMON_FIELDS = BASE_WRITABLE;
